GET http://localhost:5100/users
Authorization: Bearer 

###
POST  http://localhost:5100/users
Content-Type: application/json

{
    "name" : "Jupri",
    "email" : "jupri@gmail.com",
    "idAdmin" : "222991",
    "password" : "jupri123",
    "confPassword" : "jupri123"
}

###
GET http://localhost:5100/pasien

###
POST  http://localhost:5100/pasien
Content-Type: application/json

{
    "nik" : "123458",
    "nrk" : "123458",
    "name" : "bebel",
    "telp" : "000000",
    "jenis_kelamin" : "perempuan",
    "poli" : "Dalam",
    "dokter" : "dr.ucup, S.Kd",
    "jadwal" : "17 Desember 2022",
    "jam" : "19.00",
    "keluhan" : "Sakit dalam ringan"
}

###
PATCH http://localhost:5100/pasien/2
Content-Type: application/json

{
    "nik" : "123456",
    "name" : "Putri",
    "telp" : "000000",
    "jenis_kelamin" : "perempuan",
    "poli" : "Dalam",
    "dokter" : "dr.ucup, S.Kd",
    "jadwal" : "17 Desember 2022",
    "keluhan" : "Sakit dalam ringan"
}

###
DELETE http://localhost:5100/pasien/2

###
GET http://localhost:5100/saran

###
POST  http://localhost:5100/saran
Content-Type: application/json

{
    "name" : "Alif",
    "email" : "Alif@gmail.com",
    "subjek" : "Pendaftaran Error",
    "pesan" : "Tolong diperbaiki ya"
}